<a href="https://colab.research.google.com/github/mompaduck/Data-Analysis-with-Open-Source/blob/main/%EC%98%A4%ED%94%88%EC%86%8C%EC%8A%A4_%EB%8D%B0%EC%9D%B4%ED%84%B0_%EB%B6%84%EC%84%9D_6%EA%B0%95.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 오픈소스 기반 데이터 분석 6강 - 데이터 전처리 1

## <정리하기>

*  데이터 전처리는 원시 데이터를 분석에 적합한 형태로 정제하고 변환하는 과정이다.
*  입력 데이터의 품질이 분석 결과의 품질을 좌우한다.
*  데이터 측정은 특성 파악과 전처리 필요성 판단을 위한 기초 단계이다.
*  데이터 정제는 결측치, 잡음, 이상치 등을 처리하여 데이터 품질을 향상시킨다.
*  데이터 통합은 여러 소스의 데이터를 결합하여 일관된 데이터셋을 구성한다.
*  데이터 축소는 차원 축소, 데이터 압축 등을 통해처리 효율성을 높인다.
*  데이터 변환은 정규화, 이산화 등을 통해 분석에적합한 형태로 변형한다.
*  describe( ) 메소드를 통해 데이터의 기술통계량과구조를 파악한다.


## <데이터 전처리 프로세스 (지속적/반복적 수행)>

| 단계 | 주요 작업 | 설명 |
| :--- | :--- | :--- |
| **측정** | **구조 이해** | 다양한 측정 요소들을 활용하여 데이터의 구조와 특징을 정량적으로 파악 |
| **정제** | **정합성 확보** | 결측치 및 이상치를 처리하고, 데이터의 오류를 수정하여 데이터 간의 불일치성을 수정하는 일련의 과정 |
| **통합** | **데이터셋 결합** | 서로 다른 데이터 저장소로부터 데이터를 결합/하나의 일관된 데이터 집합을 구축하는 작업으로, 중복과 불일치를 제거 |
| **축소** | **크기 축소** | 방대한 데이터를 효율적으로 처리하기 위해 데이터의 크기를 줄이면서도 중요한 정보를 보존하는 과정 |
| **변환** | **형태 변환** | 데이터의 구조나 값을 규칙에 따라 변환하여 분석이 효율적으로 수행되도록 지원 |


## <요약 통계 지표>

| 구분 | 지표 | 설명 |
| :--- | :--- | :--- |
| **중심 경향** | **평균** | 모든 값을 더한 후 개수로 나눈 값으로, 데이터의 대표성을 나타냄. 이상치에 민감 |
| | **중앙값** | 데이터를 크기순으로 정렬했을 때 한가운데 위치한 값으로, 이상치의 영향을 덜 받음 |
| | **최빈값** | 데이터에서 가장 자주 출현하는 값으로, 범주형 데이터 분석에 유용 |
| **분산 정도** | **분산** | 각 데이터 값이 평균에서 얼마나 떨어져 있는지를 제곱하여 평균 낸 값 |
| | **표준편차** | 분산의 제곱근으로, 데이터의 흩어진 정도를 원래 단위로 표현해 직관적 |
| | **범위** | 최댓값에서 최솟값을 뺀 값으로, 데이터의 전체 분포 폭을 파악하는 데 유용 |
| | **사분위수** | 하위 25%(Q1), 50%(Q2, 중앙값), 75%(Q3) 지점을 나타내며 데이터 분포를 시각적으로 이해하는 데 활용 |
| | **사분위 범위(IQR)** | Q3에서 Q1을 뺀 값으로, 중앙 50% 구간의 범위를 나타내며 이상치 탐지에 활용 |

## <기타 통계 지표>

### 기타 통계 지표

| 지표 | 설명 |
| :--- | :--- |
| **합계** | 모든 데이터 값을 더한 값으로, 데이터 총합을 빠르게 확인할 때 사용 |
| **개수** | 데이터 항목 수를 나타내며, 결측치 여부 및 데이터 완전성 점검에 유용 |
| **최댓값** | 데이터 집합에서 가장 큰 값으로, 데이터의 상한 경계를 확인하는 데 도움 |
| **최솟값** | 데이터 집합에서 가장 작은 값으로, 데이터의 하한 경계를 확인하는 데 도움 |
| **왜도** | 데이터 분포가 평균을 중심으로 대칭적인지, 한쪽으로 치우쳤는지를 나타내는 지표 |
| **첨도** | 데이터 분포의 뾰족한 정도를 측정하며, 이상치의 빈도를 파악하는 데 유용 |

---

### <describe() 메소드 >

| 데이터 유형 | 제공 통계량 | 설명 |
| :--- | :--- | :--- |
| **수치형 데이터** | **count** | 데이터 개수 (결측치 제외) |
| | **mean** | 평균 |
| | **std** | 표준편차 |
| | **min** | 최솟값 |
| | **25%** | 제1사분위수(Q1), 하위 25% 위치값 |
| | **50%** | 제2사분위수(Q2), 중앙값(median), 하위 50% 위치값 |
| | **75%** | 제3사분위수(Q3), 하위 75% 위치값 |
| | **max** | 최댓값 |
| **범주형 데이터** | **count** | 데이터 개수 (결측치 제외) |
| | **unique** | 고유값(unique) 개수 |
| | **top** | 최빈값 |
| | **freq** | 최빈값의 빈도 |

In [ ]:
## 데이터 전처리의 예

import pandas as pd
from sklearn.cluster import KMeans

data = {'나이':[25,30,22,35,40,50,28,33,45,55],
        '소득':[3000,4000,2800,5000,6000,7000,3200,4500,6200,7200]
}

df = pd.DataFrame(data)
kmeans = KMeans(n_clusters = 3, random_state = 42)
df['군집'] = kmeans.fit_predict(df[['나이', '소득']])

print(df)

   나이    소득  군집
0  25  3000   1
1  30  4000   1
2  22  2800   1
3  35  5000   0
4  40  6000   2
5  50  7000   2
6  28  3200   1
7  33  4500   0
8  45  6200   2
9  55  7200   2

In [ ]:
## describe()메소드의 활용
import pandas as pd
import numpy as np

data = {
    'name': ['김민수', '이지영', '박준호', '최서연', '정도윤'],
    'age': [25, 30, 28, 22, 35],
    'city': ['서울', '부산', '인천', '서울', '대전'],
    'score': [90, 85, 95, 80, np.nan]
}
df = pd.DataFrame(data)

print(df.describe())

print(df.describe(include=[np.number]))
print(df.describe(include=['object']))

             age      score
count   5.000000   4.000000
mean   28.000000  87.500000
std     4.949747   6.454972
min    22.000000  80.000000
25%    25.000000  83.750000
50%    28.000000  87.500000
75%    30.000000  91.250000
max    35.000000  95.000000
             age      score
count   5.000000   4.000000
mean   28.000000  87.500000
std     4.949747   6.454972
min    22.000000  80.000000
25%    25.000000  83.750000
50%    28.000000  87.500000
75%    30.000000  91.250000
max    35.000000  95.000000
       name city
count     5    5
unique    5    4
top     김민수   서울
freq      1    2

### 6-1 데이터 훑어보기

In [ ]:
import pandas as pd
import numpy as np

data = {
    'name': ['김민수', '이지영', '박준호', '최서연', '정도윤'],
    'age': [25, 30, 28, 22, 35],
    'city': ['서울', '부산', '인천', '서울', '대전'],
    'score': [90, 85, 95, 80, np.nan]
}
df = pd.DataFrame(data)

# 데이터 측정
print(df.describe())

# 모든 데이터 타입 측정
print(df.describe(include='all'))

# 수치형 데이터 측정
print(df.describe(include=[np.number]))

# 범주형 데이터 측정
print(df.describe(include=['object']))

# 특정 열 분석
df['score'].describe()

             age      score
count   5.000000   4.000000
mean   28.000000  87.500000
std     4.949747   6.454972
min    22.000000  80.000000
25%    25.000000  83.750000
50%    28.000000  87.500000
75%    30.000000  91.250000
max    35.000000  95.000000
       name        age city      score
count     5   5.000000    5   4.000000
unique    5        NaN    4        NaN
top     김민수        NaN   서울        NaN
freq      1        NaN    2        NaN
mean    NaN  28.000000  NaN  87.500000
std     NaN   4.949747  NaN   6.454972
min     NaN  22.000000  NaN  80.000000
25%     NaN  25.000000  NaN  83.750000
50%     NaN  28.000000  NaN  87.500000
75%     NaN  30.000000  NaN  91.250000
max     NaN  35.000000  NaN  95.000000
             age      score
count   5.000000   4.000000
mean   28.000000  87.500000
std     4.949747   6.454972
min    22.000000  80.000000
25%    25.000000  83.750000
50%    28.000000  87.500000
75%    30.000000  91.250000
max    35.000000  95.000000
       name city
count     5    5
unique    5    4
top     김민수   서울
freq      1    2

count     4.000000
mean     87.500000
std       6.454972
min      80.000000
25%      83.750000
50%      87.500000
75%      91.250000
max      95.000000
Name: score, dtype: float64

### 6-2 DataFrame 열 선택 및 **조작**

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}
df = pd.DataFrame(data)

# 특정 열 선택
selected_df = df[['이름','학과', '학점']]
selected_df

# DataFrame 열순서 변경
reordered_cols = df[['학과','이름', '학년', '학점', '동아리']]
reordered_cols

# DataFrame 열이름 변경
df_renamed = df.rename(columns={'이름': '학생명', '학점': '평점', '동아리': '과외활동'})
df_renamed

   학생명  학년   평점     학과   과외활동
0  김철수   1  4.2  컴퓨터공학  프로그래밍
1  이영희   2  3.8    경영학   독서토론
2  박민수   3  4.5   전자공학   로봇공학
3  최지훈   4  3.9     의학   봉사활동
4  정소희   2  3.5    심리학   음악감상

### 6-3 DataFrame 행 선택

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

df = pd.DataFrame(data)

#DataFrame 인덱스 지정
df = df.set_index('이름')
df

#DataFrame 행 선택
df.loc['김철수']
df.loc[['김철수', '이영희']]
df.loc['김철수':'박민수']


#DataFrame 위치 기반 행 선택
df.iloc[1]
df.iloc[[2,3]]
df.iloc[1:3]

#DataFrame 조건 기반 선택
df.loc[[True, False, True, False, False]]

print(df[['학점', '학년']])
df['학점']>= 4.0

df[df['학년'] == 2]

df[(df['학년'] == 2) & (df['학점'] >= 3.7)]

      학점  학년
이름
김철수  4.2   1
이영희  3.8   2
박민수  4.5   3
최지훈  3.9   4
정소희  3.5   2

     학년   학점   학과   동아리
이름
이영희   2  3.8  경영학  독서토론

### 6-4 DataFrame 정렬

In [ ]:
import pandas as pd

data = {
    "이름": ["김철수", "이영희", "박민수", "최지훈", "정소희"],
    "학년": [1, 2, 3, 4, 2],
    "학점": [4.2, 3.8, 4.5, 3.9, 3.5],
    "학과": ["컴퓨터공학", "경영학", "전자공학", "의학", "심리학"],
    "동아리": ["프로그래밍", "독서토론", "로봇공학", "봉사활동", "음악감상"]
}

df = pd.DataFrame(data)

#DataFrame 인덱스 지정
df = df.set_index('이름')
df

#DataFrame 단일 열 오름차순, 내림차순 정렬
df.sort_values(by='학점')
df.sort_values(by='학점', ascending=False)

#DataFrame 복수 열 오름차순, 내림차순 정렬
df.sort_values(by=['학년', '학점'], ascending=[True, False])

#DataFrame 인덱스 기분 오른차순, 내림차순 정렬
df.sort_index(ascending=False)

     학년   학점     학과    동아리
이름
최지훈   4  3.9     의학   봉사활동
정소희   2  3.5    심리학   음악감상
이영희   2  3.8    경영학   독서토론
박민수   3  4.5   전자공학   로봇공학
김철수   1  4.2  컴퓨터공학  프로그래밍

## 6-5 실습 시나리오 - Kaggle을 활용한 데이터 수집 및 측정

- Kaggle([https://www.kaggle.com](https://www.kaggle.com)) 회원 가입
- Kaggle 접근 토큰 생성(API 키)

### Kaggle API 키 업로드

In [2]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"duckmompa","key":"f0cfdeac18ace24d6628614eea6b6881"}'}

### Kaggle API 키 사용을 위한 Colab 환경 설정

In [3]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

### Kaggle 데이터셋 다운로드

In [4]:
!kaggle competitions download -c store-sales-time-series-forecasting

!unzip store-sales-time-series-forecasting.zip

Downloading store-sales-time-series-forecasting.zip to /content
100% 21.4M/21.4M [00:00<00:00, 132MB/s]

Archive:  store-sales-time-series-forecasting.zip
  inflating: holidays_events.csv
  inflating: oil.csv
  inflating: sample_submission.csv
  inflating: stores.csv
  inflating: test.csv
  inflating: train.csv
  inflating: transactions.csv

### Kaggle 데이터셋 DataFrame 로드 및 살펴보기

In [ ]:
import pandas as pd

# Grocery Sales 데이터 DataFrame 로드
train = pd.read_csv('train.csv')
stores = pd.read_csv('stores.csv')
transactions = pd.read_csv('transactions.csv')
oil = pd.read_csv('oil.csv')
holidays_events = pd.read_csv('holidays_events.csv')

# 판매 데이터 살펴보기
train.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000888 entries, 0 to 3000887
Data columns (total 6 columns):
 #   Column       Dtype
---  ------       -----
 0   id           int64
 1   date         object
 2   store_nbr    int64
 3   family       object
 4   sales        float64
 5   onpromotion  int64
dtypes: float64(1), int64(3), object(2)
memory usage: 137.4+ MB

### Kaggle 데이터셋 측정

In [ ]:
# 판매 데이터 기본 통계량
train.describe()

# 매장 데이터 기본 정보
stores.head()

# 원유 가격 데이터 기본 정보
oil.head()

         date  dcoilwtico
0  2013-01-01         NaN
1  2013-01-02       93.14
2  2013-01-03       92.97
3  2013-01-04       93.12
4  2013-01-07       93.20